services:
  - type: web
    name: advocacia-backend
    runtime: docker
    repo: https://github.com/joaocastro0429/advocacia_v3.git
    plan: free
    dockerContext: ./backEnd
    dockerfilePath: ./backEnd/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://advocacia:advocacia%40ad@advocacia-db:5432/advocacia
      - key: JWT_SECRET
        generateValue: true

  - type: web
    name: advocacia-frontend
    runtime: docker
    repo: https://github.com/SEU_USUARIO/SEU_REPO
    plan: free
    dockerContext: ./frontEnd
    dockerfilePath: ./frontEnd/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://advocacia-backend.onrender.com

databases:
  - name: advocacia-db
    plan: free
