// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Avoid failing during install/build when DATABASE_URL is not set yet.
    // Migrations will still fail later until DATABASE_URL is configured correctly.
    url:
      process.env.DATABASE_URL ||
      "postgresql://user:pass@localhost:5432/db?schema=public",
  },
});
