// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` does not need a live DB connection, but Prisma config
    // will try to resolve DATABASE_URL. On Render, the DB env may not be
    // available during build for Blueprint-provisioned databases.
    // We use a placeholder URL for build-time, and the real DATABASE_URL at runtime.
    url:
      process.env.DATABASE_URL ||
      "postgresql://user:pass@127.0.0.1:1/db?schema=public",
  },
});
